services:
  backend:
    container_name: webdesignacademy-backend
    restart: unless-stopped
    image: dexter.fit.vutbr.cz/webdesignacademy/webdesignacademy-backend
    env_file:
      - .env
    volumes:
      - ./storage:/app/storage
      - type: bind
        source: ./lessons
        target: /app/lessons
        read_only: true
        bind:
          create_host_path: false
    networks:
      - webdesignacademyNetwork

  frontend:
    container_name: webdesignacademy-frontend
    restart: unless-stopped
    image: dexter.fit.vutbr.cz/webdesignacademy/webdesignacademy-frontend
    depends_on:
      - backend
    networks:
      - webdesignacademyNetwork

  proxy:
    container_name: webdesignacademy-proxy
    image: nginx:1.19
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
    networks:
      - webdesignacademyNetwork
      - network

networks:
  network:
    name: kristyna-dev
    external: true
  webdesignacademyNetwork:
    name: webdesignacademyNetwork
