events {}

http {
    include mime.types;

    upstream be {
        server webdesignacademy-backend:3000;
    }

    upstream fe {
        server webdesignacademy-frontend:80;
    }

    server {
        listen 80;

        include /etc/nginx/mime.types;

        location /wda/api/ {
            proxy_pass http://be/api/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /wda {
            proxy_pass http://fe/wda/;
        }
    }
}
