FROM node:22-alpine

RUN npm install -g pnpm

WORKDIR /app

WORKDIR /app/frontend

COPY apps/frontend/package.json ./
RUN pnpm install

COPY apps/frontend/ ./

ENV PORT=5173

EXPOSE 5173

CMD ["pnpm", "run", "dev", "--", "--host"]
