FROM node:22-alpine

RUN npm install -g pnpm

WORKDIR /app

RUN mkdir -p storage

COPY package.json ./
RUN pnpm install

COPY . ./

ENV NODE_ENV=development
ENV PORT=3000

EXPOSE 3000

CMD ["node", "--watch", "src/server.js"]
